### ISSUE TITLE
Automatic DB update on libreelec 8.90.008 does not work

### ISSUE THREAD

**Issue by MarcusRoeckrath** [mediathekview/plugin.video.mediathekview#102]
After upgrading libreelec from 8.2.5 to 8.90.008 the automatic or "update on start" DB update stopped working. Now I switched to manual DB update.

**Comment by MarcusRoeckrath** [comment]
Same on liberelec 8.90.009.

**Comment by MarcusRoeckrath** [comment]
Where is the option for update interval in the settings window which in my memory have existed in previous version of the addon.

In settings.xml I can find a line for this option:
<setting id="updinterval">2</setting>

**Comment by jochen-01** [comment]
Since I did not get automatic updates working, I've set up something -- uncommon -- to solve it for me.
In the user configuration (settings.xml) there is a setting named "updatetrigger". It accepts true or false.
If it is "true" update takes place. The update process resets the setting to "false". Therefore all I had to do is writing a small script to set this to "true" whenever I want mediathekview to update it's database.

`cd /storage/.kodi/userdata/addon_data/plugin.video.mediathekview

sed -e 's/setting id="updatetrigger" default="true">false</setting id="updatetrigger" default="true">true</g' settings.xml > settings.xml-new && mv settings.xml-new set
tings.xml`

Adding a crontab entry automates it. Done.
I left the update settings in the GUI "manual".

**Comment by alex1702** [comment]
nice hack ^^

**Comment by jochen-01** [comment]
Works better than the original behavior. I have every possibility of crontab to decide when updates shall take place.

**Comment by MarcusRoeckrath** [comment]
Thanks for the idea which works fine here. Beside creating a regularly cron job I put it into /storage/autostart.sh (with delay of 30 seconds).

I'm wondering why this problems occurs with 8.95 and hasn't be seen on 8.2 although there wasn't an update of mediathekview itself.

Maybe the author of the mediathekview addon is making the same change to the settings file while the code in the app does not work anymore for some reason.

I had written to the mediathekview team, who are working on the mediathekview program for pc and accepted the kodi mediathekview app as official client in january 18. They will discuss internally how to deal with the actual situation.

**Comment by MarcusRoeckrath** [comment]
Several minutes ago a user posted in the mediathekview forum a workaroud that fixed the problem for him; I post the original german comment from him:

"Das Problem bei mir ist, dass das MediathekView-Addon die letzte Benutzeraktivität in den Einstellungen speichert (in “lastactivity”). Der Typ von “lastactivity” ist auf “number” gestellt, aber es wird versucht, bei einer Benutzeraktivität die aktuelle Zeit als String zu speichern. Das scheitert bei mir, und deshalb wird die Zeit der Benutzterinaktivität falsch berechnet.

Bei mir hat es geholfen, in der Datei “%APPDATA%\Kodi\addons\plugin.video.mediathekview\resources\settings.xml” den “type” der “lastactivity” von “number” auf “text” zu ändern und Kodi neu zu starten. Das MediathekView-Addon geht im Coding eh davon aus, dass es beim Auslesen der Eigenschaft “lastactivity” einen String zurückbekommt.

Ob Ihr von dem gleichen Problem betroffen seid, erkennt Ihr daran, dass in der Datei “%APPDATA%\Kodi\userdata\addon_data\plugin.video.mediathekview\settings.xml” der Eintrag “<setting id=“lastactivity”>0</setting>” zu finden ist (die Null ist wichtig, bei jeder anderen Zahl seid Ihr von einem anderen Problem betroffen).

Da ich Kodi nicht unter Linux nutze, wäre es super, wenn jemand bestätigen könnte, dass dort das gleiche Problem existiert und die Pfade zu den beiden o. g. Dateien posten könnte."

**Comment by jochen-01** [comment]
O.k., es scheint, als wären die Nutzer von mediathekview sowieso alle im deutschprachigen Raum ansässig...
Ich habe den Ansatz mal getestet. Dazu habe ich meinen cron job disabled. Dann die Typ-Änderung der Variablen vorgenommen und im AddOn wieder auf automatische Updates umgestellt. Letztendlich dann ein Kodi-Neustart.
Ergebnis: Um 2:00 Uhr letzte Nacht fand eine vollständige Aktualisiserung statt -- gut.
Die aber um 4:00, 6:00, 8:00... erwarteten Differenz-Aktualisiserungen blieben leder aus.
Ich werde vorerst wieder meinen cron Ansatz in Betrieb nehmen.
Den von Dir gewünschten Pfad kann ich Dir nur für ein Odroid-Linux (CoreELEC) liefern:
~/.kodi/addons/plugin.video.mediathekview/resources/settings.xml

**Comment by MarcusRoeckrath** [comment]
Today I got the update to release 0.6.0 and now an every start I get an "Mediathekview-Error".

In kodi.log I can find this lines:

2019-03-08 10:19:46.750 T:3869680496   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python ca
llback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named kodiaddon
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathekview
/service.py", line 29, in <module>
                                                from resources.lib.service import MediathekViewServi
ce
                                              File "/storage/.kodi/addons/plugin.video.mediathekview
/resources/lib/service.py", line 12, in <module>
                                                from resources.lib.kodi.kodiaddon import KodiService

                                            ImportError: No module named kodiaddon
                                            -->End of Python script error report<--

Wetekplay2 running LibreElec 9.0.1

**Comment by tuxpoldo** [comment]
@MarcusRoeckrath : Please see #115 - the problem is known - unfortunately the Pull-Request in the official Kodi Repo was buggy because of a strange behaviour of git running on non case sensitive filesystems: the changes from #89 cased many files to be renamed to lower case. When creating the pull request for the official Kodi Repo, git did not transfer the file rename of the files in the directories `resources/lib/base` and `resources/lib/kodi`.

You can fix the problem by renaming all files in both directories to lowercase. I'm working on a new pull request fixing the problem. As an alternative you may also reinstall the version 0.6.0 from the [mediathekview beta repository](https://mediathekview.de/download/) or directly by downloading the [0.6.0 release zip here](https://github.com/mediathekview/plugin.video.mediathekview/releases/download/release-0.6.0/plugin.video.mediathekview-0.6.0.zip).

**Comment by tuxpoldo** [comment]
Pull Request [#2329](https://github.com/xbmc/repo-plugins/pull/2329) in [xbmc/repo-plugins](https://github.com/xbmc/repo-plugins) has been filed.

**Comment by MarcusRoeckrath** [comment]
Downloaded manually and it works fine now. Thanks.
