### ISSUE TITLE
sqlite - database disk image is malformed

### ISSUE THREAD

**Issue by Spacewalker2** [mediathekview/plugin.video.mediathekview#121]
Hello and first of all thanks for the amazing add-on.

I get this `Error Contents: database disk image is malformed` in my kodi.log so I thought I delete the sqlite file and let the add-on recreate it but I didn't find the sqlite file maybe I overlooked it and maybe there is a better way to do this too. Please help me here.

**Comment by tuxpoldo** [comment]
Hi @Spacewalker2 !

No problem: the location of the sqlite database depends upon your system and may very from platform to platform. First of all you have to locate your _userdata_ path. In [this Wiki Page](https://kodi.wiki/view/Userdata) you will find information where the _userdata_ path is located.

from where you have to move to `addon_data/plugin.video.mediathekview/` where you will find the file `filmliste-v2.db` - this is the database file you want to delete.

Try to find out what happened: is there enough free space in the file system? Since the database is about 270-300MB, you should have at least enough place to hold the database and also the update files when downloaded. Let's say that you should have at least additional 500MB free

**Comment by Spacewalker2** [comment]
It seems it does the trick. Thanks. There is enough space available so I'm not really sure what caused it. If I found out I'll report here.
