### ISSUE TITLE
Mediathek Update DB not available

### ISSUE THREAD

**Issue by codingPF** [mediathekview/plugin.video.mediathekview#144]
Hi,

the request to the MV update DB is failing since yesterday (7.4) evening. Tried manual in a browser with no luck as well.

Can someone look into the issue?

ERROR: [plugin.video.mediathekview-0.6.2:Updater]: Failure downloading https://liste.mediathekview.de/filmliste-v2.db.bz2

Thanks

**Comment by Marmos76** [comment]
I do have the problem since a couple of **months**.
It seems to me that MV wants to download to a certain folder /tmp/ where it has not access rights.
I do not know how it was organized previously even it formerly had these rights or if downloaded the new filmliste-v2.db.bz2 to a local user folder with respectively permission. As it may is supposed to do. But in the MV python module I have not found anything that directs to this (or any folder). 

Thus my guess is, that some other interface wants to do so. But here end my skills and also willing. Even if thing it is sad. The youtupe-app gives me almost a want to watch. 

Good luck and cheers, Martin

**Comment by codingPF** [comment]
Hi,

the Server is up again and provide the data as usually. Everything is working fine.

Thanks!
