### ISSUE TITLE
SPMC 16.7.3 / Dependencies not met

### ISSUE THREAD

**Issue by fred0r** [mediathekview/plugin.video.mediathekview#74]
As i didnt was able to find a similar Post enywhere:
i'm using SPMC (Kodi) 16.7.3 on FireTV and this Add-on isnt installable because of 'dependencies are not met'.

**Comment by alex1702** [comment]
the addon was developed for krypton (17.x) and laia (18.x) . we need your debug log

**Comment by tuxpoldo** [comment]
Any information about the version of SPMC?

**Comment by fred0r** [comment]
@alex1702 : afaik i have to possibilty to get this from the firetv
@tuxpoldo : SPMC-16.7.4

**Comment by tuxpoldo** [comment]
OK - SPMC 16 is based on Kodi 16 so there is no compatibility. The publication guidelines for Kodi Addons allowed only to publish new addons starting from the current version of Kodi. When this addon was published for the first time, the Kodi-Repository did not accept submissions for Kodi < 17. Because of this, it is not possible to satisfy the dependencies for older versions.

**Comment by fred0r** [comment]
i'm now using the 'regular kodi' on the firetv (17.x) and now it works as it should.
